### ISSUE TITLE
MPI job results in deadlock

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaDiagnostics.jl#27]
https://buildkite.com/clima/climaatmos-ci/builds/18781#018f6277-2bcc-4e4b-b772-d00dc568cdcd is taking 40 min to run (it normally takes ~7).

**Comment by Sbozzolo** [comment]
`interpolate` contains a `MPI.Reduce` and every process has to run it, otherwise the root process will wait for all the other ones.
