### ISSUE TITLE
Callbacks `condition` does not reflect if the diagnostic is computed/written to file.

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaDiagnostics.jl#37]
It would be really nice if we could faithfully query whether a callback should be called/executed, via, `cb.condition`, as is done in SciMLBase.

This, together with some small changes in ClimaAtmos, would allow us to implement a fully general benchmarking function to ClimaTimesteppers: https://github.com/CliMA/ClimaTimeSteppers.jl/issues/106.

**Comment by Sbozzolo** [comment]
I think we have that: if you have a `ScheduledDiagnostic` `diag`, `diag.compute_schedule(integrator)` will return `true` if the diagnostic has to be computed at the given state/time. Similarly with `diag.output_schedule(integrator)`

**Comment by charleskawczynski** [comment]
Ah, ok, great. Maybe it'd be as simple as `cb.condition(integrator) = any(x->x.diagnostics_handler.scheduled_diagnostics.compute_schedule(integrator), ::DiagnosticsCallbacks)`? (we could define a new `DiagnosticsCallbacks` type instead of using a closure)

**Comment by Sbozzolo** [comment]
Yes, I think so. If you want to find if compute or output has to be performed, you'll have to add `output_schedule` too (you can have output without compute depending on respective frequencies).

The one minor snag is that the actual SciML callback that we add to the integrator already has a `cb.condition`, and this condition is:
```
condition = (_, _, _) -> true
```
This is essentially to hand down the control on things are run to `orchestrate_diagnostics` (which uses the compute and output schedules).

**Comment by Sbozzolo** [comment]
Here's the relevant code we would change:
https://github.com/CliMA/ClimaDiagnostics.jl/blob/43ca4f1de1c74f6aae8c7b6b6c793666fa49445a/src/clima_diagnostics.jl#L241-L257
